package com.pocketide.sessions.transcripts

import com.pocketide.sessions.SESSION_A
import com.pocketide.sessions.SESSION_B

/** Transcript lines shaped like the agents' own files (fields as their shipped code writes them). */
object Fixtures {
    const val WORKTREE_A = "/work/alice__demo/$SESSION_A"
    const val WORKTREE_B = "/work/alice__demo/$SESSION_B"
    const val CLAUDE_SESSION = "c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"

    /** A screenshot as agents store it: megabytes of base64 in one JSON string. */
    val SCREENSHOT = "iVBORw0KGgoAAAANSUhEUgAA" + "A".repeat(300_000)

    private fun claude(type: String, uuid: String, time: String, message: String, extra: String = "") =
        """{"parentUuid":null,"isSidechain":false,"userType":"external","cwd":"$WORKTREE_A","sessionId":"$CLAUDE_SESSION",""" +
            """"version":"2.1.281","gitBranch":"pocket/claude/2026-09-24-login-fix",$extra"type":"$type","message":$message,""" +
            """"uuid":"$uuid","timestamp":"$time"}"""

    private fun usage(input: Int, created: Int, read: Int, output: Int) =
        """"usage":{"input_tokens":$input,"cache_creation_input_tokens":$created,"cache_read_input_tokens":$read,"output_tokens":$output,"service_tier":"standard"}"""

    val claude: String = listOf(
        """{"type":"summary","summary":"Login fix","leafUuid":"a5"}""",
        claude("user", "u1", "2026-09-24T05:00:00.000Z", """{"role":"user","content":"Fix the login bug on the settings screen"}"""),
        claude(
            "assistant", "a1", "2026-09-24T05:00:02.000Z",
            """{"id":"msg_01A","type":"message","role":"assistant","model":"claude-opus","content":[{"type":"thinking","thinking":"Look at the login code first.","signature":"sig"}],${usage(10, 1000, 2000, 5)}}""",
        ),
        claude(
            "assistant", "a2", "2026-09-24T05:00:03.000Z",
            """{"id":"msg_01A","type":"message","role":"assistant","model":"claude-opus","content":[{"type":"text","text":"I'll check the login code."}],${usage(10, 1000, 2000, 40)}}""",
        ),
        claude(
            "assistant", "a3", "2026-09-24T05:00:04.000Z",
            """{"id":"msg_01A","type":"message","role":"assistant","model":"claude-opus","content":[{"type":"tool_use","id":"toolu_1","name":"Read","input":{"file_path":"$WORKTREE_A/app/Login.kt"}}],${usage(10, 1000, 2000, 60)}}""",
        ),
        claude(
            "user", "u2", "2026-09-24T05:00:05.000Z",
            """{"role":"user","content":[{"tool_use_id":"toolu_1","type":"tool_result","content":"class Login { fun refresh() = Unit }"}]}""",
            extra = """"toolUseResult":{"type":"text","file":{"filePath":"$WORKTREE_A/app/Login.kt"}},""",
        ),
        """{"parentUuid":"u2","type":"assistant","message":{"id":"msg_01B",""",
        claude(
            "assistant", "a4", "2026-09-24T05:00:06.000Z",
            """{"id":"msg_01B","type":"message","role":"assistant","model":"claude-opus","content":[{"type":"tool_use","id":"toolu_2","name":"Bash","input":{"command":"./gradlew test","description":"Run the tests"}}],${usage(5, 0, 3000, 20)}}""",
        ),
        claude(
            "user", "u3", "2026-09-24T05:01:00.000Z",
            """{"role":"user","content":[{"type":"text","text":"Here is a screenshot of the bug"},{"type":"image","source":{"type":"base64","media_type":"image/png","data":"$SCREENSHOT"}}]}""",
        ),
        claude(
            "user", "u4", "2026-09-24T05:01:30.000Z",
            """{"role":"user","content":"<local-command-caveat>Caveat: the messages below were generated by the user while running local commands.</local-command-caveat>"}""",
            extra = """"isMeta":true,""",
        ),
        claude(
            "user", "u5", "2026-09-24T05:02:00.000Z",
            """{"role":"user","content":"<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>sonnet</command-args>"}""",
        ),
        claude("user", "u6", "2026-09-24T05:02:01.000Z", """{"role":"user","content":"<local-command-stdout>Set model to sonnet</local-command-stdout>"}"""),
        """{"isSidechain":true,"sessionId":"$CLAUDE_SESSION","type":"assistant","message":{"id":"msg_side","role":"assistant","content":[{"type":"text","text":"Subagent notes"}],${usage(1, 0, 0, 1)}},"uuid":"s1","timestamp":"2026-09-24T05:02:30.000Z"}""",
        claude(
            "assistant", "a5", "2026-09-24T05:03:00.000Z",
            """{"id":"msg_01C","type":"message","role":"assistant","model":"claude-opus","content":[{"type":"text","text":"Fixed: the token was not refreshed."}],${usage(7, 0, 0, 12)}}""",
        ),
        """{"type":"file-history-snapshot","messageId":"a5","snapshot":{"trackedFileBackups":{}},"isSnapshotUpdate":false}""",
        "",
    ).joinToString("\n")

    private fun codex(time: String, type: String, payload: String) = """{"timestamp":"$time","type":"$type","payload":$payload}"""

    val codex: String = listOf(
        codex(
            "2026-09-24T06:00:00.000Z", "session_meta",
            """{"session_id":"0199a1b2-c3d4-7e5f-8a9b-0c1d2e3f4a5b","id":"0199a1b2-c3d4-7e5f-8a9b-0c1d2e3f4a5b","timestamp":"2026-09-24T06:00:00.000Z","cwd":"$WORKTREE_B","originator":"codex_vscode","cli_version":"0.154.0","source":"vscode","model_provider":"openai","base_instructions":{"text":"You are Codex, a coding agent."},"git":{"commit_hash":"abc123","branch":"pocket/codex/2026-09-24-dark-theme"}}""",
        ),
        codex("2026-09-24T06:00:00.500Z", "turn_context", """{"cwd":"$WORKTREE_B","approval_policy":"on-request","sandbox_policy":{"type":"danger-full-access"},"model":"gpt-5-codex"}"""),
        codex(
            "2026-09-24T06:00:01.000Z", "response_item",
            """{"type":"message","role":"developer","content":[{"type":"input_text","text":"<permissions instructions>Ask before running commands.</permissions instructions>"}]}""",
        ),
        codex(
            "2026-09-24T06:00:01.000Z", "response_item",
            """{"type":"message","role":"user","content":[{"type":"input_text","text":"# AGENTS.md instructions for $WORKTREE_B\n\n<INSTRUCTIONS>\nUse Kotlin.\n</INSTRUCTIONS>"},{"type":"input_text","text":"<environment_context>\n  <cwd>$WORKTREE_B</cwd>\n  <shell>bash</shell>\n</environment_context>"}]}""",
        ),
        codex(
            "2026-09-24T06:00:02.000Z", "response_item",
            """{"type":"message","role":"user","content":[{"type":"input_text","text":"Add a dark theme toggle"},{"type":"input_text","text":"<image>"},{"type":"input_image","image_url":"data:image/png;base64,$SCREENSHOT"},{"type":"input_text","text":"</image>"}]}""",
        ),
        codex("2026-09-24T06:00:02.000Z", "event_msg", """{"type":"user_message","message":"Add a dark theme toggle","images":["data:image/png;base64,AAAA"]}"""),
        codex("2026-09-24T06:00:05.000Z", "response_item", """{"type":"reasoning","summary":[{"type":"summary_text","text":"Planning the toggle"}],"content":null,"encrypted_content":"gAAAAB"}"""),
        codex(
            "2026-09-24T06:00:06.000Z", "response_item",
            """{"type":"function_call","name":"shell","arguments":"{\"command\":[\"bash\",\"-lc\",\"rg -n theme app/src\"],\"workdir\":\"$WORKTREE_B\"}","call_id":"call_1"}""",
        ),
        codex("2026-09-24T06:00:07.000Z", "response_item", """{"type":"function_call_output","call_id":"call_1","output":"app/src/Theme.kt:3: val dark = false"}"""),
        codex(
            "2026-09-24T06:00:08.000Z", "event_msg",
            """{"type":"token_count","info":{"total_token_usage":{"input_tokens":1200,"cached_input_tokens":800,"output_tokens":90,"reasoning_output_tokens":40,"total_tokens":1290},"last_token_usage":{"input_tokens":1200,"cached_input_tokens":800,"output_tokens":90,"reasoning_output_tokens":40,"total_tokens":1290},"model_context_window":272000},"rate_limits":null}""",
        ),
        "this line is not JSON {",
        codex(
            "2026-09-24T06:00:09.000Z", "response_item",
            """{"type":"custom_tool_call","status":"completed","call_id":"call_2","name":"apply_patch","input":"*** Begin Patch\n*** Update File: app/src/Theme.kt\n@@\n-val dark = false\n+val dark = true\n*** Add File: app/src/Toggle.kt\n+class Toggle\n*** End Patch\n"}""",
        ),
        codex("2026-09-24T06:00:10.000Z", "response_item", """{"type":"message","role":"assistant","content":[{"type":"output_text","text":"Added the toggle in Settings."}],"phase":"final_answer"}"""),
        codex("2026-09-24T06:00:10.000Z", "event_msg", """{"type":"agent_message","message":"Added the toggle in Settings."}"""),
        codex(
            "2026-09-24T06:00:11.000Z", "event_msg",
            """{"type":"token_count","info":{"total_token_usage":{"input_tokens":2500,"cached_input_tokens":1600,"output_tokens":150,"reasoning_output_tokens":60,"total_tokens":2650},"last_token_usage":{"input_tokens":1300,"cached_input_tokens":800,"output_tokens":60,"reasoning_output_tokens":20,"total_tokens":1360},"model_context_window":272000},"rate_limits":null}""",
        ),
        codex(
            "2026-09-24T07:00:00.000Z", "event_msg",
            """{"type":"token_count","info":{"total_token_usage":{"input_tokens":300,"cached_input_tokens":0,"output_tokens":20,"reasoning_output_tokens":0,"total_tokens":320},"last_token_usage":{"input_tokens":300,"cached_input_tokens":0,"output_tokens":20,"reasoning_output_tokens":0,"total_tokens":320},"model_context_window":272000},"rate_limits":null}""",
        ),
        codex("2026-09-24T07:00:01.000Z", "response_item", """{"type":"web_search_call","status":"completed","action":{"type":"search","query":"material 3 dark theme"}}"""),
        codex(
            "2026-09-24T07:00:02.000Z", "response_item",
            """{"type":"local_shell_call","call_id":"c3","status":"completed","action":{"type":"exec","command":["bash","-lc","./gradlew assembleDebug"],"timeout_ms":null,"working_directory":null}}""",
        ),
        codex("2026-09-24T07:00:03.000Z", "world_state", """{"full":true,"state":{}}"""),
        "",
    ).joinToString("\n")

    /** Newer Codex versions also write one usage record per response; those are preferred. */
    val codexWithRecords: String = listOf(
        codex("2026-09-24T06:00:00.000Z", "session_meta", """{"id":"t1","timestamp":"2026-09-24T06:00:00.000Z","cwd":"$WORKTREE_B","originator":"codex_vscode","cli_version":"0.160.0"}"""),
        codex(
            "2026-09-24T06:00:01.000Z", "token_usage_record",
            """{"thread_id":"t1","turn_id":"x","session_id":"t1","root_turn_id":"x","response_id":"r1","usage":{"input_tokens":100,"cached_input_tokens":0,"output_tokens":10,"reasoning_output_tokens":0,"total_tokens":110},"turn_token_usage":{"input_tokens":100,"cached_input_tokens":0,"output_tokens":10,"reasoning_output_tokens":0,"total_tokens":110},"thread_token_usage":{"input_tokens":100,"cached_input_tokens":0,"output_tokens":10,"reasoning_output_tokens":0,"total_tokens":110}}""",
        ),
        codex(
            "2026-09-24T06:00:02.000Z", "event_msg",
            """{"type":"token_count","info":{"total_token_usage":{"input_tokens":999,"cached_input_tokens":0,"output_tokens":99,"reasoning_output_tokens":0,"total_tokens":1098},"last_token_usage":{"input_tokens":1,"cached_input_tokens":0,"output_tokens":1,"reasoning_output_tokens":0,"total_tokens":2},"model_context_window":1}}""",
        ),
        codex(
            "2026-09-24T06:00:03.000Z", "token_usage_record",
            """{"thread_id":"t1","turn_id":"y","session_id":"t1","root_turn_id":"y","response_id":"r2","usage":{"input_tokens":200,"cached_input_tokens":0,"output_tokens":20,"reasoning_output_tokens":0,"total_tokens":220},"turn_token_usage":{"input_tokens":200,"cached_input_tokens":0,"output_tokens":20,"reasoning_output_tokens":0,"total_tokens":220},"thread_token_usage":{"input_tokens":300,"cached_input_tokens":0,"output_tokens":30,"reasoning_output_tokens":0,"total_tokens":330}}""",
        ),
        "",
    ).joinToString("\n")

    /** Antigravity's transcript.jsonl, as its own documentation describes the steps. */
    fun antigravity(worktree: String): String = listOf(
        """{"step_index":0,"source":"USER_EXPLICIT","type":"USER_INPUT","status":"DONE","created_at":"2026-09-24T08:00:00Z","content":"Make the header sticky","media":[{"mime_type":"image/png","uri":"file:///root/.gemini/antigravity/brain/conv/media/shot.png"},{"mime_type":"text/plain","uri":"file:///root/notes.txt"}]}""",
        """{"step_index":1,"source":"MODEL","type":"PLANNER_RESPONSE","status":"DONE","created_at":"2026-09-24T08:00:05Z","content":"I'll update the header styles.","thinking":"Sticky positioning.","tool_calls":[{"name":"view_file","args":{"AbsolutePath":"$worktree/src/Header.css"}},{"name":"run_command","args":{"CommandLine":"npm test","Cwd":"$worktree"}}]}""",
        """{"step_index":2,"source":"SYSTEM","type":"VIEW_FILE","status":"DONE","created_at":"2026-09-24T08:00:06Z","content":"header { top: 0 } in $worktree/src/Header.css","truncated_fields":["content"]}""",
        "not json at all",
        """{"step_index":3,"source":"MODEL","type":"PLANNER_RESPONSE","status":"DONE","created_at":"2026-09-24T08:01:00Z","content":"Done. The header now stays on top."}""",
        "",
    ).joinToString("\n")
}
