#!/usr/bin/env python3
"""Draws every PocketAgent brand asset from branding/tokens.json.

There is one artboard -- 512 units, two brackets around a four-point spark -- and everything
else is that artboard scaled. The launcher icon, the themed icon, the Android 12+ splash, the
notification silhouette, the Play listing image and the Linux desktop icon are all emitted here,
so none of them can drift away from the others by being edited on its own.

    pip install cairosvg pillow
    python3 tools/make_brand.py
    python3 tests/brand-assets-test.py

The test needs nothing beyond the standard library and runs in CI; this generator needs the two
packages above and runs on a machine with them. That split is deliberate: the artwork is
regenerated rarely and checked on every push.
"""
import io
import json
import os
import struct
import zlib

import cairosvg
from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRANDING = os.path.join(HERE, "branding")
RES = os.path.join(HERE, "app", "res")
ASSETS = os.path.join(HERE, "app", "assets")

T = json.load(open(os.path.join(BRANDING, "tokens.json")))
B, G = T["brand"], T["geometry"]
ART = G["artboard"]
MARK, TOP, BOTTOM = B["mark"], B["tile_top"], B["tile_bottom"]

GENERATED = "Generated by tools/make_brand.py from branding/tokens.json. Do not edit by hand."


# ---------------------------------------------------------------- the mark, once
def spark_path(scale=1.0, dx=0.0, dy=0.0):
    """The four-point spark, as one closed path of quadratic curves."""
    c, r, q = ART / 2, G["spark_radius"], G["spark_control"]
    p = lambda x, y: f"{round(x * scale + dx, 2):g} {round(y * scale + dy, 2):g}"
    return (f"M{p(c, c - r)} Q{p(c + q, c - q)} {p(c + r, c)} Q{p(c + q, c + q)} {p(c, c + r)} "
            f"Q{p(c - q, c + q)} {p(c - r, c)} Q{p(c - q, c - q)} {p(c, c - r)} Z")


def place(canvas, width):
    """Scale and offset that centre the mark at `width` across on a `canvas` square.

    The mark is wider than it is tall, and its bounding circle's radius is exactly half its
    width, so asking for a width also pins the circle every Android safe-zone rule is written
    against. Sizes are chosen against what the surface actually shows: an adaptive icon is
    masked to the central 72 of its 108 dp, so 54 dp across is three quarters of the tile a
    person sees, not half of a canvas nobody sees.
    """
    scale = (width / 2) / G["mark_radius"]
    return scale, (canvas - ART * scale) / 2


def svg_mark(colour, scale=1.0, dx=0.0, dy=0.0):
    """Brackets plus spark as SVG elements, in the colour given."""
    def move(path):
        out, numbers = [], path.replace(",", " ").split()
        for token in numbers:
            if token[0] in "ML":
                out.append(token[0] + f"{round(float(token[1:]) * scale + dx, 2):g}")
            else:
                out.append(f"{round(float(token) * scale + dy, 2):g}")
        return " ".join(out)

    width = round(G["bracket_stroke"] * scale, 2)
    return (f'<g fill="none" stroke="{colour}" stroke-width="{width:g}" stroke-linecap="round" '
            f'stroke-linejoin="round">'
            f'<path d="{move(G["bracket_left"])}"/><path d="{move(G["bracket_right"])}"/></g>'
            f'<path d="{spark_path(scale, dx, dy)}" fill="{colour}"/>')


def svg_tile_mark(colour, width_fraction):
    """The mark centred on the 512 artboard at a share of its width."""
    scale, offset = place(ART, ART * width_fraction)
    return svg_mark(colour, scale=scale, dx=offset, dy=offset)


def svg_document(size, body, background=None):
    tile = ""
    if background == "square":
        tile = f'<rect width="{ART}" height="{ART}" fill="url(#tile)"/>'
    elif background == "rounded":
        tile = (f'<rect width="{ART}" height="{ART}" rx="{G["tile_corner"]}" fill="url(#tile)"/>'
                f'<rect x="3" y="3" width="{ART - 6}" height="{ART - 6}" rx="{G["tile_corner"] - 2}" '
                f'fill="none" stroke="#FFFFFF" stroke-opacity="0.12" stroke-width="6"/>')
    gradient = ""
    if tile:
        gradient = (f'<defs><linearGradient id="tile" x1="0" y1="0" x2="{ART}" y2="{ART}" '
                    f'gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="{TOP}"/>'
                    f'<stop offset="1" stop-color="{BOTTOM}"/></linearGradient></defs>')
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
            f'viewBox="0 0 {ART} {ART}">\n  <!-- {GENERATED} -->\n  {gradient}{tile}\n  {body}\n</svg>\n')


# ---------------------------------------------------------------- Android vector drawables
def vector(size_dp, colour, width_dp):
    """A VectorDrawable of the mark alone, `width_dp` across and centred on a `size_dp` canvas.

    Every width here is chosen against what its surface shows: 54 dp inside an adaptive icon,
    whose mask leaves 72 dp of the 108 dp canvas visible; 132 dp inside the splash's 192 dp
    circle; 22 dp of a 24 dp notification canvas, which is Android's own figure.
    """
    scale, offset = place(size_dp, width_dp)
    stroke = round(G["bracket_stroke"], 2)
    paths = []
    for key in ("bracket_left", "bracket_right"):
        paths.append(f'        <path android:pathData="{G[key]}" android:strokeWidth="{stroke:g}" '
                     f'android:strokeColor="{colour}" android:strokeLineCap="round" '
                     f'android:strokeLineJoin="round"/>')
    paths.append(f'        <path android:pathData="{spark_path()}" android:fillColor="{colour}"/>')
    body = "\n".join(paths)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- {GENERATED} -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp" android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="{size_dp}" android:viewportHeight="{size_dp}">\n'
            f'    <group android:scaleX="{round(scale, 6):g}" android:scaleY="{round(scale, 6):g}"\n'
            f'        android:translateX="{round(offset, 4):g}" android:translateY="{round(offset, 4):g}">\n'
            f'{body}\n'
            f'    </group>\n'
            f'</vector>\n')


def icon_vector():
    """The whole app icon -- teal tile and bone mark -- as one drawable, for use inside the app."""
    scale, offset = place(ART, ART * 0.586)
    stroke = round(G["bracket_stroke"] * scale, 2)
    paths = []
    for key in ("bracket_left", "bracket_right"):
        moved = " ".join(
            (token[0] + f"{round(float(token[1:]) * scale + offset, 2):g}") if token[0] in "ML"
            else f"{round(float(token) * scale + offset, 2):g}"
            for token in G[key].replace(",", " ").split())
        paths.append(f'        <path android:pathData="{moved}" android:strokeWidth="{stroke:g}" '
                     f'android:strokeColor="{MARK}" android:strokeLineCap="round" '
                     f'android:strokeLineJoin="round"/>')
    paths.append(f'        <path android:pathData="{spark_path(scale, offset, offset)}" '
                 f'android:fillColor="{MARK}"/>')
    r = G["tile_corner"]
    tile = (f'M{r},0 L{ART - r},0 A{r},{r} 0 0 1 {ART},{r} L{ART},{ART - r} '
            f'A{r},{r} 0 0 1 {ART - r},{ART} L{r},{ART} A{r},{r} 0 0 1 0,{ART - r} '
            f'L0,{r} A{r},{r} 0 0 1 {r},0 Z')
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- {GENERATED} -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    xmlns:aapt="http://schemas.android.com/aapt"\n'
            f'    android:width="96dp" android:height="96dp"\n'
            f'    android:viewportWidth="{ART}" android:viewportHeight="{ART}">\n'
            f'    <path android:pathData="{tile}">\n'
            f'        <aapt:attr name="android:fillColor"><gradient android:type="linear"\n'
            f'            android:startX="0" android:startY="0" android:endX="{ART}" android:endY="{ART}">\n'
            f'            <item android:offset="0" android:color="{TOP}"/>\n'
            f'            <item android:offset="1" android:color="{BOTTOM}"/></gradient></aapt:attr>\n'
            f'    </path>\n'
            f'    <group>\n' + "\n".join(paths) + f'\n    </group>\n</vector>\n')


# ---------------------------------------------------------------- writing
def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote", os.path.relpath(path, HERE))


def png(svg_text, size, path, rounded=False, circle=False):
    raw = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=size * 4, output_height=size * 4)
    image = Image.open(io.BytesIO(raw)).convert("RGBA")
    if circle:
        mask = Image.new("L", image.size, 0)
        from PIL import ImageDraw
        ImageDraw.Draw(mask).ellipse((0, 0, image.size[0] - 1, image.size[1] - 1), fill=255)
        image.putalpha(mask)
    image = image.resize((size, size), Image.LANCZOS)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    buffer = io.BytesIO()
    image.save(buffer, "PNG", optimize=True)
    with open(path, "wb") as handle:
        handle.write(tag_srgb(buffer.getvalue()))
    print("wrote", os.path.relpath(path, HERE), f"{size}x{size}")


def tag_srgb(data):
    """Splice an sRGB chunk in after IHDR.

    Pillow will not write one, and without it the colour of a Play listing image is left to
    whatever the viewer assumes. Rendering intent 0 is perceptual, which is what artwork wants.
    """
    body = b"sRGB" + bytes([0])
    chunk = struct.pack(">I", 1) + body + struct.pack(">I", zlib.crc32(body))
    end_of_ihdr = 8 + 12 + struct.unpack(">I", data[8:12])[0]
    return data[:end_of_ihdr] + chunk + data[end_of_ihdr:]


def main():
    # 0.586 of the tile: enough to read at 48 px, short of the corner radius at every size.
    full_rounded = svg_document(ART, svg_tile_mark(MARK, 0.586), background="rounded")
    full_square = svg_document(ART, svg_tile_mark(MARK, 0.586), background="square")

    # Branding folder: the sources a designer would open.
    write(os.path.join(BRANDING, "pocketagent-mark.svg"), full_rounded)
    for name, canvas, width, colour in (("adaptive-foreground.svg", 432, 216, MARK),
                                        ("splash-foreground.svg", 864, 396, MARK),
                                        ("notification.svg", 96, 88, "#FFFFFF")):
        scale, offset = place(ART, width / canvas * ART)
        write(os.path.join(BRANDING, name),
              svg_document(canvas, svg_mark(colour, scale=scale, dx=offset, dy=offset)))
    png(full_square, 512, os.path.join(BRANDING, "play-store-icon.png"))

    # Android vectors.
    write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), vector(108, MARK, 54))
    write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), vector(108, "#FFFFFFFF", 54))
    write(os.path.join(RES, "drawable", "ic_splash_pocketagent.xml"), vector(288, MARK, 132))
    write(os.path.join(RES, "drawable", "ic_stat_pocketagent.xml"), vector(24, "#FFFFFFFF", 22))
    write(os.path.join(RES, "drawable", "pocketagent_icon.xml"), icon_vector())

    # The adaptive background, and the flat colour the splash window needs.
    write(os.path.join(RES, "drawable", "launcher_gradient.xml"),
          '<?xml version="1.0" encoding="utf-8"?>\n'
          f'<!-- {GENERATED} -->\n'
          '<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">\n'
          f'    <gradient android:type="linear" android:angle="315"\n'
          f'        android:startColor="{TOP}" android:endColor="{BOTTOM}"/>\n'
          '</shape>\n')
    write(os.path.join(RES, "values", "ic_launcher_background.xml"),
          '<?xml version="1.0" encoding="utf-8"?>\n'
          f'<!-- {GENERATED} -->\n'
          '<resources>\n'
          f'    <color name="ic_launcher_background">{B["tile_flat"]}</color>\n'
          '</resources>\n')

    # Legacy launcher bitmaps, and the icon the Linux side shows.
    for density, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        png(full_rounded, size, os.path.join(RES, f"mipmap-{density}", "ic_launcher.png"))
        png(full_square, size, os.path.join(RES, f"mipmap-{density}", "ic_launcher_round.png"), circle=True)
    png(full_rounded, 512, os.path.join(ASSETS, "pocketagent-mark.png"))

    # The Linux desktop's wallpaper: the same mark, on the same ground the desktop paints
    # behind it, so the edges of a "fit" wallpaper meet the root window without a seam.
    ground, deep = T["desktop"]["ground"], T["desktop"]["ground_deep"]
    scale, offset = place(ART, ART * 0.62)
    wallpaper = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1600" viewBox="0 0 1600 1600">\n'
        f'  <!-- {GENERATED} -->\n'
        f'  <defs><radialGradient id="glow"><stop offset="0" stop-color="{TOP}" stop-opacity="0.34"/>'
        f'<stop offset="1" stop-color="{deep}" stop-opacity="0"/></radialGradient></defs>\n'
        f'  <rect width="1600" height="1600" fill="{ground}"/>\n'
        f'  <circle cx="800" cy="700" r="820" fill="url(#glow)"/>\n'
        f'  <g transform="translate(544 384)">{svg_mark(MARK, scale=scale, dx=offset, dy=offset)}</g>\n'
        f'  <text x="800" y="900" text-anchor="middle" font-family="DejaVu Sans,sans-serif" '
        f'font-weight="bold" font-size="76" fill="{T["desktop"]["on_ground"]}">PocketAgent</text>\n'
        f'  <text x="800" y="972" text-anchor="middle" font-family="DejaVu Sans,sans-serif" '
        f'font-size="34" fill="{T["desktop"]["on_ground_muted"]}">Ubuntu 24.04 LTS \u00b7 Linux</text>\n'
        f'</svg>\n')
    write(os.path.join(BRANDING, "wallpaper.svg"), wallpaper)
    raw = cairosvg.svg2png(bytestring=wallpaper.encode(), output_width=1600, output_height=1600)
    flat = Image.new("RGB", (1600, 1600), ground)
    art = Image.open(io.BytesIO(raw)).convert("RGBA")
    flat.paste(art, (0, 0), art)
    flat.save(os.path.join(ASSETS, "wallpaper.jpg"), "JPEG", quality=92, optimize=True)
    print("wrote", os.path.relpath(os.path.join(ASSETS, "wallpaper.jpg"), HERE), "1600x1600")


if __name__ == "__main__":
    main()
