package com.pocketagent.mobile;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/** Host fixtures for protocol boundaries. Uses real JSON-Java, never android.jar stubs. */
public final class AgentProtocolTest {
    private static int assertions;

    public static void main(String[] args) throws Exception {
        wireFixtures();
        codexVersionedSessionPolicy(args.length == 0 ? Paths.get(".") : Paths.get(args[0]));
        shellArgumentsStayLiteral();
        projectNamesStaySingleComponents();
        loginLinksStayOnProviderIdentityHosts();
        conversationScope();
        modelCatalogVariants();
        displayControls();
        System.out.println("PASS AgentProtocolTest (" + assertions + " assertions)");
    }

    private static void wireFixtures() throws Exception {
        // Codex app-server uses JSON-RPC semantics but omits the jsonrpc property.
        JSONObject codex = AgentProtocol.request(false, 10, "thread/start",
                AgentProtocol.codexThreadParams("/home/coder/Projects/demo", false));
        equivalent("{\"id\":10,\"method\":\"thread/start\",\"params\":{\"cwd\":\"/home/coder/Projects/demo\","
                + "\"approvalPolicy\":\"untrusted\",\"sandbox\":\"workspace-write\"}}", codex);
        check(codex.get("id") instanceof Number, "numeric server identifiers must remain numeric");

        JSONObject acp = AgentProtocol.request(true, "request-7", "session/prompt",
                AgentProtocol.object("sessionId", "session-fixture", "prompt",
                        AgentProtocol.array(AgentProtocol.object("type", "text", "text", "Build a page"))));
        equivalent("{\"jsonrpc\":\"2.0\",\"id\":\"request-7\",\"method\":\"session/prompt\","
                + "\"params\":{\"sessionId\":\"session-fixture\",\"prompt\":[{\"type\":\"text\",\"text\":\"Build a page\"}]}}", acp);

        JSONObject notification = AgentProtocol.request(true, null, "session/cancel",
                AgentProtocol.object("sessionId", "session-fixture"));
        equivalent("{\"jsonrpc\":\"2.0\",\"method\":\"session/cancel\",\"params\":{\"sessionId\":\"session-fixture\"}}", notification);
        check(!notification.has("id"), "notifications omit id, including null id");

        equivalent("{\"id\":0,\"result\":{\"decision\":\"decline\"}}",
                AgentProtocol.response(false, 0, AgentProtocol.object("decision", "decline"), false));
        equivalent("{\"jsonrpc\":\"2.0\",\"id\":\"permission-4\",\"result\":{\"outcome\":{\"outcome\":\"cancelled\"}}}",
                AgentProtocol.response(true, "permission-4", AgentProtocol.object("outcome",
                        AgentProtocol.object("outcome", "cancelled")), false));
        JSONObject error = AgentProtocol.response(true, "unknown-method", AgentProtocol.object(
                "code", -32601, "message", "Method not supported"), true);
        equivalent("{\"jsonrpc\":\"2.0\",\"id\":\"unknown-method\",\"error\":{\"code\":-32601,\"message\":\"Method not supported\"}}", error);
        check(!error.has("result"), "error responses cannot also report success");

        // Prompts and tool output may contain strings that resemble new JSON records.
        String content = "Line one\n\"}\n{\"method\":\"evil\"}\r\nहेलो 👋 \\ end";
        String wire = AgentProtocol.request(false, "unicode", "turn/start", AgentProtocol.object(
                "threadId", "thread-fixture", "input", AgentProtocol.array(
                        AgentProtocol.object("type", "text", "text", content)))).toString();
        check(wire.indexOf('\n') < 0 && wire.indexOf('\r') < 0, "one envelope must remain one JSONL record");
        String roundTrip = new JSONObject(wire).getJSONObject("params").getJSONArray("input")
                .getJSONObject(0).getString("text");
        equal(content, roundTrip, "JSONL round trip must preserve multiline Unicode text");
    }

    private static void codexVersionedSessionPolicy(Path project) throws Exception {
        // Generated by the installed Codex 0.154.0 binary, not copied from moving web docs.
        // The web examples currently use different enum spellings; sending those to the
        // pinned binary prevents every chat from opening. Exercise the production builder.
        Path source = project.resolve("tests/agent-protocol/schemas/codex-0.154.0/ThreadStartParams.json");
        JSONObject schema = new JSONObject(new String(Files.readAllBytes(source), StandardCharsets.UTF_8));
        JSONObject definitions = schema.getJSONObject("definitions");
        JSONArray sandboxModes = definitions.getJSONObject("SandboxMode").getJSONArray("enum");
        JSONArray policies = definitions.getJSONObject("AskForApproval").getJSONArray("oneOf")
                .getJSONObject(0).getJSONArray("enum");
        for (boolean full : new boolean[]{false, true}) {
            JSONObject params = AgentProtocol.codexThreadParams("/home/coder/Projects/demo", full);
            check(contains(policies, params.getString("approvalPolicy")),
                    "production approvalPolicy is rejected by installed Codex 0.154.0");
            check(contains(sandboxModes, params.getString("sandbox")),
                    "production sandbox is rejected by installed Codex 0.154.0");
            equal("untrusted", params.getString("approvalPolicy"), "even full access must retain approval policy");
            equal(full ? "danger-full-access" : "workspace-write", params.getString("sandbox"),
                    "full access must only follow the explicit full-access branch");
        }
        check(!contains(policies, "unlessTrusted"), "fixture must detect incompatible website approval spelling");
        check(!contains(sandboxModes, "workspaceWrite"), "fixture must detect incompatible website sandbox spelling");
    }

    private static boolean contains(JSONArray values, String needle) {
        for (int i = 0; i < values.length(); i++) if (needle.equals(values.optString(i))) return true;
        return false;
    }

    private static void shellArgumentsStayLiteral() throws Exception {
        String[] values = {"", "a b", "don't-expand", "$(printf injected)", "`printf injected`",
                "'; printf injected; #", "a\nb", "semi; amp& pipe| >file <input", "हेलो/✨", "${PATH}", "back\\slash"};
        for (String value : values) {
            Process process = new ProcessBuilder("bash", "-c", "printf '%s' " + AgentProtocol.quote(value))
                    .redirectErrorStream(true).start();
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            try (InputStream input = process.getInputStream()) {
                byte[] buffer = new byte[1024];
                int count;
                while ((count = input.read(buffer)) != -1) output.write(buffer, 0, count);
            }
            check(process.waitFor() == 0, "quoted fixture must remain a valid shell argument");
            equal(value, new String(output.toByteArray(), StandardCharsets.UTF_8),
                    "shell metacharacters must never execute or expand");
        }
    }

    private static void projectNamesStaySingleComponents() {
        for (String value : new String[]{"demo", "A1", "project.v2-test_3", repeat('a', 80)}) {
            equal(value, AgentProtocol.project(value), "valid project name changed");
        }
        for (String value : new String[]{null, "", ".", "..", "../outside", "/tmp/project", "a/b", "a\\b",
                "space name", "-option", "a;echo", "a\nnext", "x\u0000y", repeat('a', 81)}) {
            boolean rejected = false;
            try { AgentProtocol.project(value); } catch (IllegalArgumentException expected) { rejected = true; }
            check(rejected, "unsafe project component was accepted");
        }
    }

    private static void loginLinksStayOnProviderIdentityHosts() {
        String[][] allowed = {{"codex", "https://auth.openai.com/oauth/authorize?state=fixture"},
                {"codex", "https://chatgpt.com/device"}, {"cursor", "https://cursor.com/login"},
                {"cursor", "https://auth.cursor.sh/authorize"}, {"claude", "https://claude.ai/oauth/authorize"},
                {"claude", "https://console.anthropic.com/login"},
                {"antigravity", "https://accounts.google.com/o/oauth2/auth"}};
        for (String[] pair : allowed) check(AgentProtocol.loginUrl(pair[0], pair[1]), "official identity URL was rejected");
        String[] rejected = {"http://auth.openai.com/login", "https://openai.com.evil.invalid/login",
                "https://evilopenai.com/login", "https://openai.com@evil.invalid/login",
                "https://evil@openai.com/login", "https://evil.invalid/?next=https://openai.com",
                "https://openai.com\\@evil.invalid/", "file:///tmp/login", "javascript:alert(1)",
                "https://127.0.0.1/login", "https://openaı.com/login", "not a URL", null};
        for (String value : rejected) check(!AgentProtocol.loginUrl("codex", value), "untrusted identity URL was accepted");
        check(!AgentProtocol.loginUrl("unknown", "https://openai.com/login"), "unknown providers must not inherit identity trust");
        check(!AgentProtocol.loginUrl("cursor", "https://chatgpt.com/login"), "another provider's identity must not become a login button");
    }

    private static void modelCatalogVariants() throws Exception {
        JSONArray source = new JSONArray("[{\"modelId\":\"acp-model\",\"id\":\"wrong\",\"name\":\"ACP model\"},"
                + "{\"model\":\"codex-model\",\"id\":\"wrong\",\"displayName\":\"Codex model\"},"
                + "{\"id\":\"legacy-model\"},null,\"bad row\",{}]");
        JSONArray normalized = AgentProtocol.models(source);
        check(normalized.length() == 3, "malformed model rows should not become choices");
        equal("acp-model", normalized.getJSONObject(0).getString("id"), "ACP modelId takes precedence");
        equal("codex-model", normalized.getJSONObject(1).getString("id"), "Codex model takes precedence");
        equal("Codex model", normalized.getJSONObject(1).getString("name"), "Codex displayName survives");
        equal("legacy-model", normalized.getJSONObject(2).getString("name"), "unnamed models remain identifiable");
        JSONArray excessive = new JSONArray();
        for (int i = 0; i < 150; i++) excessive.put(AgentProtocol.object("id", "model-" + i));
        check(AgentProtocol.models(excessive).length() == 100, "model menu must be bounded");
    }

    private static void conversationScope() {
        String command = "item/commandExecution/requestApproval";
        JSONObject current = AgentProtocol.object("threadId", "thread-current", "turnId", "turn-current");
        check(AgentProtocol.matchesScope(true, "thread-current", "turn-current", true, command, current, true),
                "current turn's approval must remain available");
        check(!AgentProtocol.matchesScope(true, "thread-current", "turn-current", true, command,
                AgentProtocol.object("threadId", "thread-old", "turnId", "turn-current"), true),
                "another thread must never obtain approval from this chat");
        check(!AgentProtocol.matchesScope(true, "thread-current", "turn-current", true, command,
                AgentProtocol.object("threadId", "thread-current", "turnId", "turn-old"), true),
                "an old turn must never obtain approval from the new turn");
        check(!AgentProtocol.matchesScope(true, "thread-current", "turn-current", true, command,
                AgentProtocol.object("turnId", "turn-current"), true),
                "an unscoped Codex permission must be rejected");
        check(!AgentProtocol.matchesScope(true, "thread-current", "", false, command, current, true),
                "an idle conversation must reject an old approval");
        check(!AgentProtocol.matchesScope(true, "thread-current", "", false, command,
                AgentProtocol.object("threadId", "thread-current"), true),
                "a Codex command approval without required turnId must fail closed");
        check(AgentProtocol.matchesScope(true, "thread-current", "", true, "turn/started",
                AgentProtocol.object("threadId", "thread-current", "turn", AgentProtocol.object("id", "turn-new")), false),
                "the first turn notification must establish a pending turn");
        check(!AgentProtocol.matchesScope(true, "thread-current", "", false, "turn/completed",
                AgentProtocol.object("threadId", "thread-current", "turn", AgentProtocol.object("id", "turn-old")), false),
                "a completed old turn must not rewrite idle session state");
        check(AgentProtocol.matchesScope(true, "", "", false, "account/login/completed",
                AgentProtocol.object("success", true), false), "account login events are global");
        check(AgentProtocol.matchesScope(true, "thread-current", "turn-current", true, "account/rateLimits/updated",
                AgentProtocol.object("rateLimits", new JSONObject()), false), "quota updates are global");
        check(AgentProtocol.matchesScope(false, "session-current", "", true, "session/request_permission",
                AgentProtocol.object("sessionId", "session-current"), true), "current ACP approval must remain available");
        check(!AgentProtocol.matchesScope(false, "session-current", "", true, "session/request_permission",
                AgentProtocol.object("sessionId", "session-old"), true), "old ACP session must not receive approval");
        check(!AgentProtocol.matchesScope(false, "session-current", "", true, "session/request_permission",
                new JSONObject(), true), "ACP permission must name its session");
        check(!AgentProtocol.matchesScope(false, "session-current", "", true, "session/update",
                new JSONObject(), false), "unscoped ACP deltas must not enter the chat");
        check(!AgentProtocol.matchesScope(false, "session-current", "", false, "cursor/create_plan",
                new JSONObject(), true), "an idle Cursor session must reject stale unscoped extension requests");
    }

    private static void displayControls() {
        equal("hello world", AgentProtocol.clean("\u001b[31mhello\u001b[0m \u0000world", 100),
                "terminal color/control bytes should not reach native text");
        check(AgentProtocol.clean(repeat('a', 10000), 500).length() < 600,
                "untrusted engine output must be bounded for native rendering");
    }

    private static void equivalent(String fixture, JSONObject actual) throws Exception {
        check(new JSONObject(fixture).similar(actual), "wire fixture differs: " + actual);
    }
    private static void equal(String expected, String actual, String why) {
        check(expected.equals(actual), why);
    }
    private static void check(boolean condition, String why) {
        assertions++;
        if (!condition) throw new AssertionError(why);
    }
    private static String repeat(char value, int length) {
        char[] chars = new char[length]; java.util.Arrays.fill(chars, value); return new String(chars);
    }
}
